### ISSUE TITLE
Simple transmission spectrum tutorial is missing a cell in the online docs

### ISSUE THREAD

**Issue by nborsato** [bmorris3/shone#7]
In the examples section of the **online** docs there's a discrepancy. It reads 

Suppose we want to compute transmission spectra for several atmospheric temperatures. The function interp_opacity does not take vector arguments for temperature or pressure, but we can easily vectorize it with [vmap](https://jax.readthedocs.io/en/latest/_autosummary/jax.vmap.html#jax.vmap) like this: 

Then the proceeding cell has the following code

.. code-block:: python

    label = [f"{t} K" for t in temperature]
    
    plt.figure()
    plt.semilogy(wavelength, example_opacity.T, label=label)
    plt.semilogy(wavelength, kappa_cloud * np.ones_like(wavelength), ls='--', label="Cloud")
    plt.legend()
    plt.gca().set(
        xlabel='Wavelength [µm]',
        ylabel='Opacity, $\kappa$ [cm$^2$ g$^{-1}$]'
    )

There's a missing cell here, having a look at the rst file, in the git repo, I can see there should be an additional code block with the following code

.. code-block:: python

    from jax import vmap
    # interpolate for a range of wavelengths at one pressure and temperature:
    temperature = np.array([200, 400, 600, 800])

    example_opacity = vmap(
        lambda temp: interp_opacity(wavelength, temp, pressure)
    )(temperature)
    
However, it's not present on the webdocs. Just thought I should bring it to your attention, I assume it will be a quick fix that will prevent errors in people code if they're running it for the first time.

**Comment by bmorris3** [comment]
Thanks @nborsato! I'll fix this now.

**Comment by nborsato** [comment]
I've sent DACE an email detailing the bug, I'll report back when they get back to me

**Comment by nborsato** [comment]
So I received an email from DACE saying they have fixed the bug. Their response was:

"There was actually a bug in the DACE website. The VALD entry should not be displayed in the interface since the associated file does not exist."

However, I've run into a problem that might need a sanity check from someone else. When I initiate working code, I get the following output:

from shone.opacity.dace import download_atom

download_atom(
    atom='Fe',
    charge=0,
    temperature_range=[4500, 4500]
)

2024-05-22 12:30:08,411 - ERROR - Http error: 500 Server Error: Internal Server Error for url: https://opa-webapp.obsuksprd2.unige.ch/atom/search?limit=10000&filters=%7B%7D&sort=%7B%7D
2024-05-22 12:30:08,411 - ERROR - Please contact DACE support

KeyError                                  Traceback (most recent call last)
Cell In[2], line 3
      1 from shone.opacity.dace import download_atom
----> 3 download_atom(
      4     atom='Fe',
      5     charge=0,
      6     temperature_range=[4500, 4500]
      7 )

File ~/path/to/shone/opacity/dace.py:518, in download_atom(atom, charge, line_list, temperature_range, pressure_range, version)
    488 def download_atom(atom, charge, line_list='first-found',
    489                   temperature_range=None, pressure_range=None, version=None):
    490     """
    491     Download atomic opacity data from DACE.
    492 
   (...)
    516         latest version.
    517     """
--> 518     available_line_lists = available_opacities.get_atomic_line_lists(atom)
    520     if line_list == 'first-found':
    521         line_list = sorted(list(available_line_lists)).pop()

File ~/path/to/shone/opacity/dace.py:57, in AvailableOpacities.get_atomic_line_lists(self, atom)
     56 def get_atomic_line_lists(self, atom):
---> 57     table = self.atomic
     58     return set(table[table['atom'] == atom]['line_list'])

File ~/anaconda3/envs/python311/lib/python3.11/functools.py:1001, in cached_property.__get__(self, instance, owner)
    999 val = cache.get(self.attrname, _NOT_FOUND)
   1000 if val is _NOT_FOUND:
-> 1001     val = self.func(instance)
   1002     try:
   1003         cache[self.attrname] = val

File ~/path/to/shone/opacity/dace.py:31, in AvailableOpacities.atomic(self)
     29 @cached_property
     30 def atomic(self):
---> 31     return get_atomic_database()

File ~/path/to/shone/opacity/dace.py:126, in get_atomic_database()
    124 db = Atom.query_database()
    125 table = Table(db)
--> 126 table.add_index('atom')
    127 return table

File ~/anaconda3/envs/python311/lib/python3.11/site-packages/astropy/table/table.py:1061, in Table.add_index(self, colnames, engine, unique)
   1059 if isinstance(colnames, str):
   1060     colnames = (colnames,)
-> 1061 columns = self.columns[tuple(colnames)].values()

File ~/anaconda3/envs/python311/lib/python3.11/site-packages/astropy/table/table.py:272, in TableColumns.__getitem__(self, item)
    270     return list(self.values())[item.item()]
    271 elif isinstance(item, tuple):
--> 272     return self.__class__([self[x] for x in item])
    273 elif isinstance(item, slice):
    274     return self.__class__([self[x] for x in list(self)[item]])

File ~/anaconda3/envs/python311/lib/python3.11/site-packages/astropy/table/table.py:272, in <listcomp>(.0)
    270     return list(self.values())[item.item()]
    271 elif isinstance(item, tuple):
--> 272     return self.__class__([self[x] for x in item])
    273 elif isinstance(item, slice):
    274     return self.__class__([self[x] for x in list(self)[item]])

File ~/anaconda3/envs/python311/lib/python3.11/site-packages/astropy/table/table.py:264, in TableColumns.__getitem__(self, item)
    253 """Get items from a TableColumns object.
    254 
    255 ::
   (...)
    261   tc[1:3] # <TableColumns names=('b', 'c')>
    262 """
    263 if isinstance(item, str):
--> 264     return OrderedDict.__getitem__(self, item)
    265 elif isinstance(item, (int, np.integer)):
    266     return list(self.values())[item]

KeyError: 'atom'

I've cloned both my repository and Brett's repository, and they are identical. The same error occurs in both cases. It looks like a DACE problem again, but it’s now not working for all atomic and molecular species.

**Comment by nborsato** [comment]
So, the above error has resolved itself. I can now download opacities as normal.

However, when attempting to download C from DACE, I get the following error:

ValueError: DACE said that atom C with charge 0 should be available from the line list 'VALD', but none was found when shone queried DACE. This is likely an issue with DACE. DACE reports that these other line lists should be available: {'NIST', 'Kurucz'}.

Is it possible to make shone able to query the NIST or Kurucz line lists if none is found? Or potentially add an optional argument to the download atom class to select which line list you want?

**Comment by Hoeijmakers** [comment]
Hi Nic, the download_atom method has an optional keyword.

The following line works on my machine with the current version of branch main:

`download_atom(atom='C',charge=0,line_list='Kurucz',temperature_range=[2000,2500])`.

I note that the line list string is case-sensitive, but doing it wrong gives an informative error.
